engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js

